#!/bin/bash env
# shellcheck_disable=SC2034


Color_off='\033[0m'       # Text Reset
# Regular Colors
black='\033[0;30m'        # Black
red='\033[0;31m'          # Red
green='\033[0;32m'        # Green
yellow='\033[0;33m'       # Yellow
blue='\033[0;34m'         # Blue
purple='\033[0;35m'       # Purple
cyan='\033[0;36m'         # Cyan
white='\033[0;37m'        # White

# Bold
bblack_='\033[1;30m'       # Black
bred_='\033[1;31m'         # Red
bgreen_='\033[1;32m'       # Green
byellow_='\033[1;33m'      # Yellow
bblue_='\033[1;34m'        # Blue
bpurple_='\033[1;35m'      # black
bcyan_='\033[1;36m'        # Cyan
bwhite_='\033[1;37m'       # White

# Underline
ulblack_='\033[4;30m'       # Black
ulred_='\033[4;31m'         # Red
ulgreen_='\033[4;32m'       # Green
ulyellow_='\033[4;33m'      # Yellow
ulblue_='\033[4;34m'        # Blue
ulpurple_='\033[4;35m'      # Purple
ulcyan_='\033[4;36m'        # Cyan
ulwhite_='\033[4;37m'       # White

# Background
bgblack_='\033[40m'       # Black
bgred_='\033[41m'         # Red
bggreen_='\033[42m'       # Green
bgyellow_='\033[43m'      # Yellow
bgblue_='\033[44m'        # Blue
bgpurple_='\033[45m'      # Purple
bgcyan_='\033[46m'        # Cyan
bgwhite_='\033[47m'       # White

# High Intensity
brblack='\033[0;90m'       # Black
brred='\033[0;91m'         # Red
brgreen='\033[0;92m'       # Green
bryellow='\033[0;93m'      # Yellow
brblue='\033[0;94m'        # Blue
brpurple='\033[0;95m'      # Purple
brcyan='\033[0;96m'        # Cyan
brwhite='\033[0;97m'       # White

# Bold High Intensity
bbblack='\033[1;90m'      # Black
bbred='\033[1;91m'        # Red
bbgreen='\033[1;92m'      # Green
bbyellow='\033[1;93m'     # Yellow
bbblue='\033[1;94m'       # Blue
bbpurple='\033[1;95m'     # Purple
bbcyan='\033[1;96m'       # Cyan
bbwhite='\033[1;97m'      # White

# High Intensity backgrounds
bbgblack='\033[0;100m'   # Black
bgbred='\033[0;101m'     # Red
bgbgreen='\033[0;102m'   # Green
bgbyellow='\033[0;103m'  # Yellow
bgbblue='\033[0;104m'    # Blue
bgbpurple='\033[0;105m'  # Purple
bgbcyan='\033[0;106m'    # Cyan
bgbwhite='\033[0;107m'   # White
