#!bin/bash env

PATH=$HOME/.local/npm-global/bin:$HOME/.local/bin:$PATH

# Path
case ":$PATH:" in
  *":$HOME/bin:"*) ;;
  *) export PATH="$PATH:$HOME/bin" ;;
esac

fpath=($ZSH_CUSTOM/plugins/zsh-completions/src /usr/share/bash-completion/completions $fpath)

[ -f ~/.inshellisense/key-bindings.zsh ] && source ~/.inshellisense/key-bindings.zsh
export CUNO_ROOT=$HOME//.local/opt/cuno
# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# yarn
export PATH="$HOME/.local/bin:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

#
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion nvm

BIN="$HOME/.local/bin/"

export GOPATH="$HOME/.local/go/"



source /usr/share/bash-completion/completions/incus> /dev/null 2>&1
PATH=$HOME/.local/share/pnpm:$HOME/.bun/bin:$HOME/.deno/bin:$HOME/.yarn/bin:$HOME/.local/bin:$HOME/.config/yarn/global/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/linuxbrew/.linuxbrew/bin:$PATH
export BIN=$HOME/.local/bin/
