#!/bin/zsh

# Random Color Selection
colors=(red green cyan yellow blue magenta)
rand_color=${colors[RANDOM % ${#colors[@]}]}

# Zstyle Configuration
zstyle ':completion:*' format '%F{'"$rand_color"'} ﷽       %F{limegreen}%d %f'
zstyle ':compinstall' 'filename' '$HOME/.zshcompfig'

# Basic Completion Settings
zstyle ':completion:*' completer _expand _complete _ignored _match _approximate _prefix
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' file-sort size
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' max-errors 4
zstyle ':completion:*:approximate:*' max-errors 4
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' use-compctl true
zstyle ':completion:*' verbose true


# Use modern completion system
zstyle ':completion:*' use-comp-system 'true'
zstyle ':completion:*' menu select 2

# Group matches and describe.
zstyle ':completion:*:matches' group 'yes'
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:descriptions' format '%F{'"$rand_color"'}'

# Menu Selection and Error Handling
zstyle ':completion:*' prompt '%F{'"$rand_color"'} did you mean...%f'

# List Colors for Different Item Types
zstyle ':completion:*:options' list-colors '%F{'"$rand_color"'}'
zstyle ':completion:*:commands' list-colors '%F{'"$rand_color"'}'
zstyle ':completion:*:arguments' list-colors '%F{'"$rand_color"'}'

# Cursor Color (May require additional configuration)
zstyle ':completion:*' select-prompt '%F{'"$rand_color"'}%p%f'

# Matching Strategy (Experiment for best results)
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 

# Zcompdump (Completion Cache)
zstyle ':completion:*' rehash 'true'  # Rehash completion cache when needed

# Define widget for menu-select

zmodload -i zsh/complist
_have() {
  unset -f have
  (( $+commands[\$1] ))
}

_have() {
  if typeset -f have > /dev/null; then
    unset -f have
  fi
  (( $+commands[$1] ))
}

